name: Retrieve

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  retrieve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
        coverage: none

    - name: Create composer.json
      run: |
        echo '{
          "require": {
            "rechtlogisch/tse-id-php": "^0.1",
            "symfony/console": "^7.2",
            "symfony/browser-kit": "^7.2",
            "symfony/css-selector": "^7.2",
            "symfony/http-client": "^7.2"
          }
        }' > composer.json

    - name: Install package
      run: composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-dev

    - name: Run retrieve console command
      run: vendor/bin/console tse-id:retrieve

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add changed list
        title: 'feat: list changed'
        body: |
          This PR updates the list of available TSE as of.

          Auto-generated by create-pull-request[1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: list-changed
        delete-branch: true
        add-paths: |
          current.json
