name: Retrieve TSE list (tse-id-js)

on:
  schedule:
    - cron: '0 5,17 * * *' # At 05:00 UTC and 17:00 UTC every day
  workflow_dispatch:

jobs:
  retrieve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Create package.json
      run: |
        echo '{
          "dependencies": {
            "tse-id": "^0.1"
          }
        }' > package.json

    - name: Install dependencies
      run: npm install

    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}-22
        restore-keys: |
          playwright-${{ hashFiles('package-lock.json') }}-22
          playwright-

    - name: Install Playwright
      run: npx playwright install --with-deps chromium

    - name: Set current date
      run: echo "DATE_CURRENT=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Retrieve
      run: npx tse-id -o list/${{ env.DATE_CURRENT }}.json -p

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: list-${{ env.DATE_CURRENT }}
        path: list/${{ env.DATE_CURRENT }}.json
        retention-days: 90

    - name: Check for differences
      id: diff
      shell: bash +e {0}
      run: |
        diff "list/${{ env.DATE_CURRENT }}.json" list/current.json
        EXIT_STATUS=$?
        if [ $EXIT_STATUS -eq 1 ]; then
          echo "differences=true" >> $GITHUB_OUTPUT
          echo "Differences found"
          exit 0
        elif [ $EXIT_STATUS -eq 0 ]; then
          echo "differences=false" >> $GITHUB_OUTPUT
          echo "No differences found"
          exit 0
        else
          echo "Unexpected error occured while running diff"
          exit $EXIT_STATUS
        fi

    - name: Update current.json
      if: steps.diff.outputs.differences == 'true'
      run: cp "list/${{ env.DATE_CURRENT }}.json" list/current.json

    - name: Create Pull Request
      if: steps.diff.outputs.differences == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add changed list
        title: 'feat: TSE list changed on ${{ env.DATE_CURRENT }}'
        body: |
          Updates the list of available TSE.

          Auto-generated by the GitHub workflow [retrieve.yml](../actions/workflows/retrieve.yml)
        branch: update-tse-list
        delete-branch: true
        add-paths: |
          list/current.json
          list/${{ env.DATE_CURRENT }}.json

    - name: Health check
      run: curl -sS $(echo ${{ secrets.HEALTHCHECK_URL }})
